{
 "title": "providers",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" },
   { "name": "Jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Multihash Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(storetheindex_core_ingest_multihashes{job=\"$Jobs\"}[$__rate_interval])\n",
     "legendFormat": "$Jobs"
    },
    {
     "expr": "rate(storetheindex_core_ingest_multihashes{job=\"{$Jobs}\"}[5m])\n",
     "legendFormat": "$Jobs rolling 5m"
    }
   ]
  },
  {
   "title": "total core ingest multihashes over period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(storetheindex_core_ingest_multihashes{job=\"$Jobs\"}[$__range]))"
    }
   ]
  },
  {
   "title": "increase in ingested multihashes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(storetheindex_core_ingest_multihashes{job=\"$Jobs\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "ingest announcements received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(storetheindex_ingest_change{job=\"$Jobs\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Provider count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "storetheindex_provider_count{job=\"$Jobs\"}\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Machine Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*rate(process_cpu_seconds_total{job=\"$Jobs\"}[$__rate_interval])",
     "legendFormat": "CPU percent"
    }
   ]
  },
  {
   "title": "Uptime in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time()-process_start_time_seconds{job=\"$Jobs\"}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$Jobs\"}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$Jobs\"}",
     "legendFormat": "Open File Descriptors"
    }
   ]
  },
  {
   "title": "OS Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "go_threads{job=\"$Jobs\"}"
    }
   ]
  },
  {
   "title": "Size of Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "storetheindex_core_storage_size{job=\"$Jobs\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Read path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "go-indexer-core.Get() rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(storetheindex_core_get_index_latency_count{job=\"$Jobs\"}[$__rate_interval])",
     "legendFormat": "$Jobs"
    },
    {
     "expr": "rate(storetheindex_core_get_index_latency_count{job=\"$Jobs\"}[$__rate_interval] offset 7d)",
     "legendFormat": "$Jobs 1 week ago"
    }
   ]
  },
  {
   "title": "storetheindex.find() request rate",
   "type": "timeseries",
   "description": "How many times we called find",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(storetheindex_find_latency_count{job=\"$Jobs\"}[$__rate_interval])\n",
     "legendFormat": "$Jobs"
    },
    {
     "expr": "rate(storetheindex_find_latency_count{job=\"$Jobs\"}[$__rate_interval] offset 7d)\n",
     "legendFormat": "$Jobs 1 week ago"
    }
   ]
  },
  {
   "title": "go-indexer-core.Get() latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# see https://prometheus.io/docs/practices/histograms/#quantiles\nhistogram_quantile(0.90, sum(rate(storetheindex_core_get_index_latency_bucket{job=\"$Jobs\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "p90"
    },
    {
     "expr": "# see https://prometheus.io/docs/practices/histograms/#quantiles\nhistogram_quantile(0.50, sum(rate(storetheindex_core_get_index_latency_bucket{job=\"$Jobs\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "storetheindex.find() latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# see https://prometheus.io/docs/practices/histograms/#quantiles\nhistogram_quantile(0.50, sum(rate(storetheindex_find_latency_bucket{job=\"$Jobs\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "# see https://prometheus.io/docs/practices/histograms/#quantiles\nhistogram_quantile(0.90, sum(rate(storetheindex_find_latency_bucket{job=\"$Jobs\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "go-indexer-core.Get() latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "# See https://grafana.com/blog/2020/06/23/how-to-visualize-prometheus-histograms-in-grafana/#now-show-me-the-buckets-distribution-over-time\n# and https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/\nsum(increase(storetheindex_core_get_index_latency_bucket{job=\"$Jobs\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "storetheindex.find() latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "# See https://grafana.com/blog/2020/06/23/how-to-visualize-prometheus-histograms-in-grafana/#now-show-me-the-buckets-distribution-over-time\nsum(increase(storetheindex_find_latency_bucket{job=\"$Jobs\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Indexer Cache State",
   "type": "timeseries",
   "description": "items, values, hits, misses. Only applies on the read path",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "storetheindex_core_cache_hits{job=\"$Jobs\"}",
     "legendFormat": "hits"
    },
    {
     "expr": "storetheindex_core_cache_misses{job=\"$Jobs\"}",
     "legendFormat": "misses"
    },
    {
     "expr": "storetheindex_core_cache_multihashes",
     "legendFormat": "keys"
    },
    {
     "expr": "storetheindex_core_cache_values",
     "legendFormat": "values"
    }
   ]
  },
  { "title": "Hydra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Hydra Query Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (sum(rate(hydrabooster_sti_find_provs_total{status=\"0\"}[$__rate_interval])) / sum(rate(hydrabooster_sti_find_provs_total[$__rate_interval]))) ",
     "legendFormat": "hydra query response sla"
    }
   ]
  },
  {
   "title": "Hydra Query counts",
   "type": "timeseries",
   "description": "0 means hydra failed to get any response.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status)(rate(hydrabooster_sti_find_provs_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Hydra Query SLA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum(rate(hydrabooster_sti_find_provs_total{status=\"0\"}[$__rate_interval])) / sum(rate(hydrabooster_sti_find_provs_total[$__rate_interval])))",
     "legendFormat": "success percentage"
    }
   ]
  },
  {
   "title": "Questionable charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true,
   "panels": [
    {
     "title": "total core ingest multihashes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(storetheindex_core_ingest_multihashes{job=\"$Jobs\"}[7d])",
       "legendFormat": "$Jobs rolling 7d"
      },
      {
       "expr": "increase(storetheindex_core_ingest_multihashes{job=\"$Jobs\"}[100y])",
       "legendFormat": "$Jobs all-time"
      }
     ]
    }
   ]
  }
 ]
}